package com.walmart_integration.items;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Item implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public Item() {
    }




}